
title: Tactile theme
description: Tactile is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-tactile

github:
  zip_url: https://github.com/ZzzM/HostsX/releases/download/2.8.1/HostsX.dmg
  another_url: https://github.com/ZzzM/HostsX/releases/download/2.8.1/HostsX.dmg
