default_platform(:mac)

platform :mac do
  
  lane :package do |options|
    setup(commit_sha: options[:commit_sha])
    build
    clean

  end
  
  
  private_lane :setup do |options|
    increment_version_number_in_plist(version_number: ENV["APP_VERSION"])
	  increment_build_number_in_plist(build_number: ENV["APP_VERSION"])
    set_info_plist_value(path: "#{ENV["APP_NAME"]}/Info.plist", key: "CommitSHA", value: options[:commit_sha])
  end


  private_lane :build do 
    build_app(
      clean: true,
      silent: true,
      export_method: 'mac-application')
  end

  private_lane :clean do
    sh "rm -vfr ~/Library/Developer/Xcode/Archives/*"
  end


end
