name: Venus

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
      
env:
  APP_NAME: KAI
  SPARKLE_KEY: ${{ secrets.SPARKLE_KEY }}
  BODY_PATH: BODY_PATH.md
  
jobs:

  build:
    runs-on: macos-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3.3.0
      
    - name: Setup
      uses: actions/setup-node@v3.6.0
      
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: '14.1'

    - run: |
        echo "APP_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
 
    - name: Package
      run: |
        fastlane package

    - name: Create
      run: |
        sh scripts/create_dmg.sh
       
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ${{ env.BODY_PATH }}
        files: ${{ env.APP_NAME }}.dmg
 
    - name: Appcast
      uses: actions/github-script@v6
      if: startsWith(github.ref, 'refs/tags/')
      with:
        github-token: ${{ secrets.PERSONAL_TOKEN }}
        script: |
          github.rest.repos.requestPagesBuild({
            owner: context.repo.owner,
              repo: context.repo.repo,
            })


