on:
  push:
    tags:
      - 1.*
  
  workflow_dispatch:

jobs:

  Realese:
    runs-on: macos-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.4.0
      
    - name: Package
      run: fastlane package
 
    - name: Create
      if: startsWith(github.ref, 'refs/tags/') 
      run: |
        brew install create-dmg
        create-dmg --hdiutil-quiet --app-drop-link 0 30 $APP_SCHEME.dmg $APP_SCHEME.app
 
    - name: Upload
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: ${{ github.ref }}(${GITHUB_SHA::7})
        files: $APP_SCHEME.dmg
 
    - name: Appcast
      if: startsWith(github.ref, 'refs/tags/')
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
   
env:
  APP_SCHEME: ${{ secrets.APP_SCHEME }}
