on:
  push:
    tags:
      - 1.*
  
  workflow_dispatch:

jobs:

  Realese:
    runs-on: macos-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.4.0
      
#     - name: Package
#       run: |
#         fastlane run increment_build_number build_number:${GITHUB_SHA::7}
#         fastlane package
 
#     - name: Create
#       run: |
#         brew install create-dmg
#         create-dmg --hdiutil-quiet --app-drop-link 0 30 $APP_SCHEME.dmg $APP_SCHEME.app
#         ls


    - name: Vars
      id: vars
      run: |
        echo ::set-output name=version::${GITHUB_REF#refs/*/}
        echo ::set-output name=build::${GITHUB_SHA::7}

    - name: Test
      run: echo ${{ steps.vars.outputs.version }} ${{ steps.vars.outputs.build }}
 
#     - name: Upload
#       uses: softprops/action-gh-release@v1
#       with:
#         name: $${{ steps.vars.outputs.version }}(${{ steps.vars.outputs.build }})
#         files: $APP_SCHEME.dmg
 
 
#     - name: Appcast
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
   
env:
  APP_SCHEME: ${{ secrets.APP_SCHEME }}
