name: All

on:
  push:
    tags:
      - '*'
  
  workflow_dispatch:

jobs:

  Realese:
    runs-on: macos-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.4.0
      
    - run: |
        echo "APP_BUILD=${GITHUB_SHA::7}" >> $GITHUB_ENV
        
    - name: Package
      run: |
        fastlane run increment_build_number build_number:$APP_BUILD
        fastlane package

    - name: Create
      run: |
        brew install create-dmg
        echo $PWD
        create-dmg \
        --volicon AppIcon.icns \
        --hdiutil-quiet \
        --app-drop-link 0 30  \
        $APP_SCHEME.dmg $APP_SCHEME.app

    - name: Changelog
      run: | 
 
       signature=`$PWD/sign_update -s $SPARKLE_KEY KAI.dmg`
       signature=${signature%\" *}
       signature=${signature#*=\"}
       
       changelog=`cat RELEASES.md`
       changelog=${changelog%%---*}
       changelog=${changelog#*###}
       changelog="###$changelog"
       content="<!-- $APP_BUILD,$signature -->"
       
       echo "$changelog$content" > CHANGELOG.md
       
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: CHANGELOG.md
        files: ${{ env.APP_SCHEME }}.dmg
 
 
    - name: Rebuild 🚀 
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.PERSONAL_TOKEN }}
        script: |
          github.rest.repos.requestPagesBuild({
            owner: context.repo.owner,
              repo: context.repo.repo,
            })
              
env:
  APP_SCHEME: ${{ secrets.APP_SCHEME }}
  SPARKLE_KEY: ${{ secrets.SPARKLE_KEY }}
