on:
  push:
  
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
 
      - name: p
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo 123
