on:
  push:
    tags:
      - '*'
  
  workflow_dispatch:

jobs:

  Realese:
    runs-on: macos-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.4.0
      
#     - name: Package
#       run: |
#         fastlane run increment_build_number build_number:${GITHUB_SHA::7}
#         fastlane package
 
#     - name: Create
#       run: |
#         brew install create-dmg
#         create-dmg --hdiutil-quiet --app-drop-link 0 30 $APP_SCHEME.dmg $APP_SCHEME.app
#         ls


    - name: Set
      id: vars
      run: | 
        echo $PWD
        ls

        
#        version=$(defaults read $PWD/$APP_SCHEME.app/Contents/Info.plist CFBundleShortVersionString)
#        build=$(defaults read $PWD/$APP_SCHEME.app/Contents/Info.plist CFBundleVersion)
        
#         echo "APP_VERSION=$version" >> $GITHUB_ENV
#         echo "APP_BUILD=$build" >> $GITHUB_ENV

#     - name: Test
#       run: echo $APP_VERSION $APP_BUILD
 
#     - name: Upload
#       uses: softprops/action-gh-release@v1
#       with:
#         name: $APP_VERSION($APP_BUILD)
#         files: $APP_SCHEME.app
 
 
#     - name: Appcast
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
   
env:
  APP_SCHEME: ${{ secrets.APP_SCHEME }}
