name: Venus

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
      
env:
  SPARKLE_KEY: ${{ secrets.SPARKLE_KEY }}
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  BARK_KEY: ${{ secrets.BARK_KEY }}
  BARK_HOST: ${{ secrets.BARK_HOST }}
  BARK_ICON: https://raw.githubusercontent.com/ZzzM/AA/main/KAI/Assets.xcassets/AppIcon.appiconset/icon_128x128.png
  
jobs:

  build-deploy:
    runs-on: macos-15
    steps:

    - uses: actions/checkout@v4

    - name: Create DMG
      run: |
        fastlane create_dmg

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ${{ env.LOG_PATH }}
        files: ${{ env.DMG_PATH }}
 
    - name: Deploy
      uses: actions/github-script@v7
      if: startsWith(github.ref, 'refs/tags/')
      with:
        github-token: ${{ env.PERSONAL_TOKEN }}
        script: |
          github.rest.repos.requestPagesBuild({
            owner: context.repo.owner,
              repo: context.repo.repo,
            })

    - name: Bark
      uses: harryzcy/action-bark@v1
      if: success() || failure()
      with:
        status: ${{ job.status }}
        title: ${{ env.APP_NAME }} ${{ env.APP_TAG_NAME }}
        body: ${{ job.status }}
        device_key: ${{ env.BARK_KEY }}
        level: passive
        bark_server_url: ${{ env.BARK_HOST }}
        sound: alarm
        icon: ${{ env.BARK_ICON }}

