name: Venus

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
      
env:
  SPARKLE_KEY: ${{ secrets.SPARKLE_KEY }}
  PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  
jobs:

  build-deploy:
    runs-on: macos-13
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.1
      
    - name: Setup Node
      uses: actions/setup-node@v4.0.0
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1.6.0

    - name: Package
      run: |
        fastlane package

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ${{ env.BUILD_PATH }}/TMP.md
        files: ${{ env.BUILD_PATH }}/${{ env.APP_NAME }}.dmg
 
    - name: Deploy
      uses: actions/github-script@v7.0.1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        github-token: ${{ env.PERSONAL_TOKEN }}
        script: |
          github.rest.repos.requestPagesBuild({
            owner: context.repo.owner,
              repo: context.repo.repo,
            })


