name: Test


on:
  
  workflow_dispatch:
  
env:
  BARK_KEY: ${{ secrets.BARK_KEY }}
  BARK_HOST: ${{ secrets.BARK_HOST }}

jobs:

  df:
    runs-on: macos-13
    steps:
      - id: x1
        run: |
         echo 123
         exit 1

      - id: x2
        run: |
          echo Hello


      - name: Bark
        uses: monlor/bark-action@v3
        if: success() || failure()
        with:
          key: ${{ env.BARK_KEY }}
          host: ${{ env.BARK_HOST }}
          title: ${{ env.BARK_KEY }}${{ env.BARK_HOST }}
          body: ${{ job.status }}
          icon: https://raw.githubusercontent.com/ZzzM/AA/main/KAI/Assets.xcassets/AppIcon.appiconset/icon_128x128.png
