name: Test


on:
  
  workflow_dispatch:


jobs:

  df:
    runs-on: macos-13
    steps:
      - name: x1
        run: |
         echo 123

      - name: x2
        run: |
          echo Hello

      - name: notify
        if: success() || failure()
        uses: shink/bark-action@v2
        with:
          key: ${{ secrets.BARK_KEY }}
          host: ${{ secrets.BARK_HOST }}
          title: $GITHUB_REPOSITORY
          body: ${{ jobs.status }}
