name: Test


on:
  
  workflow_dispatch:


jobs:

  df:
    runs-on: macos-13
    steps:
      - name: x1
        run: |
         echo 123

      - name: x2
        run: |
          echo Hello

      - name: notify
        if: success() || failure()
        uses: monlor/bark-action@v3
        with:
          key: ${{ secrets.BARK_KEY }}
          host: ${{ secrets.BARK_HOST }}
          title: ${{ github.repository	}}
          body: ${{ job.status }}
          sound: alarm
          isArchive: 1
          icon: https://raw.githubusercontent.com/ZzzM/AA/main/KAI/Assets.xcassets/AppIcon.appiconset/icon_32x32%402x.png
