
name: Test


on:
  workflow_dispatch:
  
env:
  VV: ${{ secrets.VV }}
  TT: tt

jobs:

  build:

    runs-on: macOS-12


    steps:

      # - uses: actions/checkout@v3
      
      - name: Run a multi-line script
        run: |
          npm

          
