name: Test


on:
  
  workflow_dispatch:


jobs:

  df:
    runs-on: macos-13
    steps:
      - name: x1
        run: |
         echo 123
         exit 1

      - name: x2
        run: |
          echo Hello

      - if: success() || failure()
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$JOB_CONTEXT"
          echo "$STEPS_CONTEXT"
          echo "$RUNNER_CONTEXT"

      - name: notify
        if: success() || failure()
        uses: monlor/bark-action@v3
        with:
          key: ${{ secrets.BARK_KEY }}
          host: ${{ secrets.BARK_HOST }}
          title: ${{ github.repository	}}
          body: ${{ job.status }}
          icon: https://raw.githubusercontent.com/ZzzM/AA/main/KAI/Assets.xcassets/AppIcon.appiconset/icon_128x128.png
