
name: Test


on:
  workflow_dispatch:
  
env:
  VV: ${{ secrets.VV }}
  TT: tt

jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      # - uses: actions/checkout@v3
      
      - name: Run a multi-line script
        run: |
          echo -n "$VV" | base64 --decode --output $TT

          
      - run: |
          echo `cat $TT`
          
